### ISSUE TITLE
Support to disable specific skills, and disable artifacts.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [William758/ContentDisabler#1]
An enhancement, to allow disabling specific skills for any survivor as well as remove artifacts from the artifact list. Example: to disable one or two skills from huge skill packs that don't work well/bugged AND removing the 20+ added artifacts from content mods that you will probably never use.

**Comment by William758** [comment]
Latest update should allow you to disable skills and artifacts.

**Comment by Mr-Foxtrot** [comment]
Awesome, thanks for the update!
